### PR TITLE
Migrate to phantom-zone library

### PR DESCRIPTION
**Pull request by cap10morgan**
We moved the zip->timezone lookup data and code into a [new library called phantom-zone](https://github.com/democracyworks/phantom-zone) because we need it in ballot-scout too (so we can determine what timezone a partner is in based on their zip code).

The tests still pass in here.

Please review these changes and the new library's code. Thanks!

### CODE REVIEW

**Comment by cap10morgan** [comment]
@danielglauser Pretty rarely. It's when the USPS or state law (like if CO decides to be in DST all the time) changes what timezone a zipcode is in.

And yes, if we update that data, I think we should bump the version of this library.

**Comment by marlabrizel** [comment]
Agree on the version bump for timezone change

**Comment by danielglauser** [comment]
Is [matching the default timezone](https://github.com/democracyworks/usps-processor/blob/f46da836ce4f1b9fa1348a9db8e54895aa13ffa1/src/usps_processor/parse.clj#L21) something that we'd want to `warn` on?

**Comment by cap10morgan** [comment]
@danielglauser I don't know, maybe.

**Pull request merged**
