### PR TITLE
[EN] Start importer in a daemon, api as web, in new main.

### PR DESCRIPTION
**Pull request by ericnormand**
This branch continues the migration from Immutant to Immutant 2.
The previous version ran `immutant.daemons/daemonize` with a :singleton?
false option. Unfortunately, Immutant 2 does not allow such an
option. It is always run as a singleton, which means that if run in a
wildfly cluster, at most one version will be running on the cluster at
the same time.

If we are not using a wildfly cluster, the point is moot and the
solution in this branch is satisfactory.

If we are using a wildfly cluster, we have to think about whether
running it as a singleton is reasonable, and if not, find a new
solution.

I have asked on IRC but I got no answer. Web searches turn up nothing.

### CODE REVIEW

**Comment by cap10morgan** [comment]
LGTM

Thanks for researching the Immutant 2 differences here. Since we're currently not planning on using WildFly clustering, the difference is moot as you point out. However we should keep it in mind if we ever contemplate moving in that direction.

The importer should be fine to run multiple instances of because they're all consuming the same queue (so only one instance should get each incoming message). In fact, that's the primary scaling strategy for our components. However, with the USPS uploading scans at a rate of no more than once / hour, I doubt we'll need to scale the importer. But the redundancy without having to wait for a failover process is nice too.

**Comment by ericnormand** [comment]
Got the answer from the immutant folks themselves: daemonize never did more than doing a clean shutdown when the app shuts down, except for the singleton case, which we weren't using.

So to simulate the old behavior, run your code in a thread and set up a shutdown callback with [`var-at-exit`](http://immutant.org/documentation/current/apidoc/immutant.util.html#var-at-exit). As you said, we don't really need it for this case, but probably will in the future as we migrate our services.

**Comment by ericnormand** [comment]
[Pivotal Card](https://www.pivotaltracker.com/story/show/91626176)

**Comment by cap10morgan** [comment]
So just to be clear (given the preference for running both importer and api on every node):

1. Without WildFly clustering (current plan): `immutant.daemons/singleton-daemon` works just fine for our needs.
1. With or without WildFly clustering: We should just spin up a thread and setup an `at-exit` shutdown callback.

Should we just do option 2 now so we don't have a looming issue when/if we decide to use WildFly clustering?

**Comment by cap10morgan** [comment]
@ericnormand Thoughts on the questions above?

**Comment by ericnormand** [comment]
Yes, we should do #2.

**Comment by ericnormand** [comment]
Ok, should be good now.

**Pull request merged**
